### ISSUE TITLE
横断歩道について

### ISSUE THREAD

**Issue by AriYu** [Nishida-Lab/TC2015#54]
つくばチャレンジ２０１５では横断歩道を渡る課題がありますが、安全のためチェッカーボードによる停止指示が行われることになったようです。
そのため、完走のためにはチェッカーボードの検出が必要になりそうです。
あと数日でチェッカーボードを検出するプログラムを作成しなければなりません。
そのため、どのような手法やフローを用いるのがよいか緊急で考える必要があります。
皆さんの知恵をお借りしたいと思います。よろしくお願いします。

なにか、こういうのを使えばいけるとかあれば教えてください。
![s-](https://cloud.githubusercontent.com/assets/8924428/10840378/263506b6-7f22-11e5-87f3-1a31438dba22.jpg)

**Comment by MoriKen254** [comment]
このルール変更、ひどかったやつですね笑。クローズ！
