### ISSUE TITLE
参加レポートの執筆について

### ISSUE THREAD

**Issue by AriYu** [Nishida-Lab/TC2015#59]
参加レポートを提出したいと思いますので、各自が担当されたところを適当に書いてください。
とりあえず、ページ数は考えないでいいと思います。

お忙しいとは思いますが、よろしくお願いします。

**Comment by RyodoTanaka** [comment]
@AriYu @mum254 
締め切りは、12/7(月) でよろしくお願いします。
森田さん、大変お忙しいかと思いますが、lower_step_detectorと遠隔監視システムについて記述いただけると幸いです。よろしくお願いします。

**Comment by mum254** [comment]
承知しました。
指定フォーマットはありますか？
ない場合、何形式が望ましいですか？

**Comment by AriYu** [comment]
@mum254 
すみません。書き忘れておりました。
`add-report`ブランチで`Document/Report`にtexファイルを用意しています。
https://github.com/Nishida-Lab/TC2015/blob/add-report/Document/Report/tc2015_report.tex

その他レポートに関しての不明な点がありましたらこのissueか新しくissueをお願いします。

**Comment by mum254** [comment]
@RyodoTanaka @AriYu 
お願いがあり、早めに相談しておきます。

私の力不足で、本件Texによる清書の工数が取れないかもしれません…。
その場合でも、もちろん本文は必ず仕上げます。例えば、txtやWord形式で送付して、Texによる清書をお願いすることになるかもしれませんが、可能でしょうか？
そうなってしまう場合、〆切から遡っていつまでにお送りすれば、作業をして頂く時間を確保できそうですか？

申し訳ないのですが、リスクヘッジのため、確認させて下さい。
宜しくお願いします。

**Comment by AriYu** [comment]
@mum254 
数式などが少なければ数時間で出来ると思いますので、締め切りは同じで大丈夫です。
txt形式やword形式、どちらでも大丈夫ですが、wordの場合、画像等は別途用意して頂いて、「ここにhogehoge.pngが入る」というような感じでお願い出来ないでしょうか。

お忙しい中、申し訳ありませんがよろしくお願いします。

**Comment by mum254** [comment]
@AriYu 
ご理解頂き、ありがとうございます。こちらこそ、本来は私がやるべき仕事なのに、申し訳ないです。

画像の件、承知しました。

よろしくお願いします。

**Comment by mum254** [comment]
tex含め，工数を確保しました．ご心配おかけして申し訳ございません．
本日中に上げます．

**Comment by AriYu** [comment]
参加レポートを提出いたしましたので、このissueを閉じます。
ご協力ありがとうございました。
