### ISSUE TITLE
つくばチャレンジレポート集のIDとパスワード

### ISSUE THREAD

**Issue by MoriKen254** [Nishida-Lab/TC2015#63]
表記を教えて頂けますか？つくちゃ2015のホームページを見ると、レポート閲覧にはIDとパスワードが必要とのことなのですが、当方の過去のメールを探しても見当たらなかったもので。

すみませんが、よろしくお願いします。

**Comment by RyodoTanaka** [comment]
@MoriKen254 
現在、調査中です。少々お待ちください。
また、判明し次第、メールにてお送りします。
よろしくお願いします。

**Comment by RyodoTanaka** [comment]
@MoriKen254
メールにて、ユーザー名とパスワードをお送りしました。
ご確認をよろしくおねがいします。
また、他にもユーザー名やパスワードを知りたい方がいらっしゃれば、[RyodoTanaka](http://github.com/RyodoTanaka)まで、直接ご連絡ください。
