### ISSUE TITLE
ステア機構モデルの実現に関して

### ISSUE THREAD

**Issue by MoriKen254** [Nishida-Lab/TC2015#64]
3号機用のros_controller作成を検討中に気付いたことがあります。現状のgazeboモデルはステア機構に対応していません。
実機だと1軸回せば2つの前輪がいい感じに回っていると思いますが、gazeboで同様のリンク機構が欲しいのです。でも、ROSだと閉リンクは使えないとかなんとか。

そこで、知恵を貸してください。何かアイディアはありませんか？
目的は、「実機とgazeboで共通で使えるcontrollerを作りたい」です。

最悪は、gazeboと実機でコントローラを分けて検証すればよいので、余り神経質にならなくていいです。（その場合、gazeboのリンク機構はコントローラ側でソフト的に実装します。）

ですが、共通なのが出来たら美しいんだけどなぁ、と言うお話です。

P.S. 2016年版もこのリポジトリでいいですか？

**Comment by RyodoTanaka** [comment]
@MoriKen254 
私が考えていた方法は、
 閉リンク機構をURDFで記述するのではなく、コントローラ側で前輪の角度を計算してそれをGazeboのリンクに直接送る
というものです。
つまり、ステアリング機構の数式モデルを作り、計算してリンク角度として直接書き込むという方法です。

ちなみに、閉リンク機構は記述できないですが、複数のjoint同士の相対関係をURDFで記述する方法として、**mimic**という要素を追加するものがあるようです。ただし、やってみたことはありません。。。
http://wiki.ros.org/urdf/XML/joint

2016年度からの開発は、別リポジトリで管理しています。 -> https://github.com/CIR-KIT/third_robot_pkg
年度で分けると管理がしづらいため、ロボットごとでパッケージ管理します。
2016年度だけに特化したアプリケーション等の開発は、デモパッケージを新たに作成して行いたいと思います。ですので、今回の変更は[`third_robot_gazebo`パッケージ](https://github.com/CIR-KIT/third_robot_pkg/tree/master/third_robot_gazebo)もしくは、新たに`thurd_robot_controller`パッケージを[`thirt_robot_pkg`](https://github.com/CIR-KIT/third_robot_pkg)の下に新たに作成していただけると嬉しいです。
よろしくお願いします。

P.S. 上記のパッケージはNishida-Labではなく、CIR-KITのリポジトリに移動しておりますので、チームへの招待を送っておきます。よろしくお願いします。

**Comment by MoriKen254** [comment]
@RyodoTanaka 
早速のアイディアありがとうございます。以下、返答です。誤りがあれば教えてください。

> 閉リンク機構をURDFで記述するのではなく、コントローラ側で前輪の角度を計算してそれをGazeboのリンクに直接送る
> というものです。
> つまり、ステアリング機構の数式モデルを作り、計算してリンク角度として直接書き込むという方法です。

この方法は、

> 最悪は、gazeboと実機でコントローラを分けて検証すればよいので、余り神経質にならなくていいです。（その場合、gazeboのリンク機構はコントローラ側でソフト的に実装します。）

と記述したものと等価になるかな？と感じました。

その場合、要求仕様である

> 目的は、「実機とgazeboで共通で使えるcontrollerを作りたい」です。

をどのように実現できるのかな？と思って、issueを立ててみました^^

この方法で実装したコントローラを、実機に「そのまま」転用というのは、ごちゃごちゃしそうだなーという印象を受けています。実機で使うなら仮想リンクは不要な計算ですし、使いもしないロジックが裏で動いているのは何となく気持ち悪いw
ros_controllerの大本の設計思想では、実機もgazeboも制御対象のjointは同一種別を前提としているので、小手先でもいいからここを突いた対策ができないかな？と思案していました。

それに対しては、下さった情報である

> 複数のjoint同士の相対関係をURDFで記述する方法として、mimicという要素を追加するものがあるようです。ただし、やってみたことはありません。。。
> http://wiki.ros.org/urdf/XML/joint

をすればよさげですね。正にこういう情報が欲しかった！面白そうなので、ちょいと見てみます^^

これがダメなら、おとなしくソフトでやります。パラメータか引数あたりでフラグ立てて、内部で切り替えればいいかなーという考えです。

ありがとう！

**Comment by MoriKen254** [comment]
色々書いたけど、mimicでも結局仮想リンクと同じことですね。

やっぱりフラグで切り替えるのが最適解だと思います。

おかげで方針に迷いがなくなりました。ありがとう！

リポジトリの件も、了解です。

**Comment by RyodoTanaka** [comment]
@MoriKen254 
ソフトウェアで算出して入力するというやり方ですが、すみません、コントローラではなく、RobotHWSimのプラグインを新たに作成したら良いのではないかと考えていました。
つまり、コントローラから、RobotHW、RobotHWSimに与えられる指令値はステアの角度だけで、そこからRobotHWはWrite()で前輪操舵モータへ指令を、RobotHWSimは2つの前輪Linkに具体的な角度を算出して入力するという方法です。
やってみたことがないので、間違っていたらすみません。
よろしくお願いします。

**Comment by MoriKen254** [comment]
あ、それいいですね！その通りだと思います。
すみません、私の視野が狭かったです^^;

ほんと、助かります。

**Comment by RyodoTanaka** [comment]
お力になれて良かったです！
よろしくお願いします！！

というか、アッカーマンステア（パラレルリンクでも）のcontrollerプラグインって完成したら本家にPR送れるんじゃないですかね？
自動運転とか、今回のつくチャとかで使いたい人って結構要ると思うんですけど...どうですかね？

**Comment by MoriKen254** [comment]
面白そうですね。それを意識して組むと多分コードもきれいになりますし笑、何よりこっちも勉強になりますね。
- steer_drive_controller
- steer_robot_hw_sim(gazeboのときだけ)

という提供方法になりそうですね。

PRを通すには、少なくとも下記の点をクリアする必要がありそうです。
- バージョン
  - 一つのcontrollerに複数のinterface(steerのようにposとvelを組み合わせる等)を搭載する仕組みは、Jade以降のサポートになります。(今indigoのfr01で出来ているのは、小細工を使っているので、人様には見せられません^^;) 
  - よって、ちゃんとやるなら、こっちのシステムのバージョンを上げるべきでしょうが、既存の資産が崩れる可能性があり、悩ましいところではあります。
- 汎用性
  - どこまでパラメータでいじれるようにすれば、そこそこの多く人がいじれるのか？ある程度形になったらお話してみましょうか。
- テストコード
  - 本家のcontorollerのリポジトリを見ると、結構膨大な数のテストコードがあるみたいです汗。リクエストを通すためには、これに相当するだけのテストを全て通しておくぐらいの礼儀は示す必要がありそうですね。
- モチベーション
  - これを解決するモチベーションが長期で維持できないといけません笑。

とりあえずコメント、ちょっと意識はして見ます。

**Comment by RyodoTanaka** [comment]
@MoriKen254 

> 一つのcontrollerに複数のinterface(steerのようにposとvelを組み合わせる等)を搭載する仕組みは、Jade以降のサポートになります。(今indigoのfr01で出来ているのは、小細工を使っているので、人様には見せられません^^;) 

確かに、これがあるからindigoまでではサポートされていなかったのかもしれませんね...
ほかにも、テストコード書いたりするの大変そうですね...
ただ、テストコードの書き方は前から気になっていたので、個人的にはやってみたいです。

いずれにせよ、自分達で使えるものを作ってからですね...
つくチャが終わったらご指摘頂いた点を詰めてやってみたいです！

**Comment by MoriKen254** [comment]
> 「実機とgazeboで共通で使えるcontrollerを作りたい」

https://github.com/CIR-KIT/steer_drive_ros/issues/4 でPRまで行きました。夢が叶いましたねー。

クローズ！
